version: "2.4"
services:
  db:
    image: postgres:15.1-alpine
    ports:
      - "${DB_PORT}:5432"
    expose:
      - "${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    healthcheck:
      test: [ "CMD", "sh", "-c", "pg_isready -q -d ${DB_DATABASE} -U ${DB_USERNAME}" ]
      timeout: 45s
      interval: 1s
      retries: 10
    restart: always

  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
    restart: unless-stopped
